use resp::{Value, encode};

pub(crate) fn create_command_respons() -> String {
    let values = Value::Array(vec![
        Value::Array(vec![
            Value::String("get".to_string()),
            Value::Integer(2),
            Value::Array(vec![
                Value::String("readonly".to_string())
            ]),
            Value::Integer(1),
            Value::Integer(1),
            Value::Integer(1)
        ]),
        Value::Array(vec![
            Value::String("set".to_string()),
            Value::Integer(-3),
            Value::Array(vec![
                Value::String("write".to_string()),
                Value::String("denyoom".to_string())
            ]),
            Value::Integer(1),
            Value::Integer(1),
            Value::Integer(1),
            Value::Array(vec![
                Value::String("@write".to_string()),
                Value::String("@string".to_string()),
                Value::String("@slow".to_string())
            ])
        ]),
        Value::Array(vec![
            Value::String("del".to_string()),
            Value::Integer(-2),
            Value::Array(vec![
                Value::String("write".to_string())
            ]),
            Value::Integer(1),
            Value::Integer(-1),
            Value::Integer(1),
            Value::Array(vec![
                Value::String("@keyspace".to_string()),
                Value::String("@write".to_string()),
                Value::String("@slow".to_string())
            ])
        ]),
        Value::Array(vec![
            Value::String("keys".to_string()),
            Value::Integer(2),
            Value::Array(vec![
                Value::String("readonly".to_string()),
                Value::String("sort_for_script".to_string())
            ]),
            Value::Integer(0),
            Value::Integer(0),
            Value::Integer(0),
            Value::Array(vec![
                Value::String("@keyspace".to_string()),
                Value::String("@read".to_string()),
                Value::String("@slow".to_string()),
                Value::String("@dangerous".to_string()),
            ])
        ]),
        Value::Array(vec![
            Value::String("mset".to_string()),
            Value::Integer(-3),
            Value::Array(vec![
                Value::String("write".to_string()),
                Value::String("denyoom".to_string())
            ]),
            Value::Integer(1),
            Value::Integer(-1),
            Value::Integer(2),
            Value::Array(vec![
                Value::String("@write".to_string()),
                Value::String("@string".to_string()),
                Value::String("@slow".to_string())
            ])
        ]),
        Value::Array(vec![
            Value::String("ping".to_string()),
            Value::Integer(-1),
            Value::Array(vec![
                Value::String("stale".to_string()),
                Value::String("fast".to_string())
            ]),
            Value::Integer(0),
            Value::Integer(0),
            Value::Integer(0),
            Value::Array(vec![
                Value::String("@fast".to_string()),
                Value::String("@connection".to_string())
            ])
        ]),
        Value::Array(vec![
            Value::String("command".to_string()),
            Value::Integer(-1),
            Value::Array(vec![
                Value::String("random".to_string()),
                Value::String("loading".to_string()),
                Value::String("stale".to_string())
            ]),
            Value::Integer(0),
            Value::Integer(0),
            Value::Integer(0),
            Value::Array(vec![
                Value::String("@slow".to_string()),
                Value::String("@connection".to_string())
            ])
        ])
    ]);

    std::str::from_utf8(&encode(&values)).unwrap().parse().unwrap()
}